services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_MOCKS_ENABLED : {{ env.MOCKS_ENABLED:-false }}
      VITE_SUPABASE_URL: {{ env.VITE_SUPABASE_URL }}
      VITE_SUPABASE_PUBLISHABLE_KEY: {{ env.VITE_SUPABASE_PUBLISHABLE_KEY }}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev

